const customMapping: { [key: string]: string } = {
    php: "php",
    cs: "csharp",
    cpp: "cpp",
    js: "javascript",
    ts: "typescript",
    py: "python",
    rb: "ruby",
    java: "java",
    kt: "kotlin",
    swift: "swift",
    go: "go",
    rs: "rust",
    dart: "dart",
    lua: "lua",
    r: "r",
    scala: "scala",
    sh: "shell",
    sql: "sql",
    html: "html",
    css: "css",
    json: "json",
    yaml: "yaml",
    md: "markdown",
}

export default customMapping;